### ISSUE TITLE
what kind of resouces is this repo supposed to hold?

### ISSUE THREAD

**Issue by modernNeo** [langaracs/course-resources#6]
I am an alumni and have all my old assignments and midterms and code and textbooks but I get the feeling none of that is helpful as it probably breaks school policy re plagiarism and copyrights ....so what resources is this repo supposed to contain?

**Comment by ENTPRESTIGIOUS** [comment]
Notes or useful resources found online (not textbooks).

_Originally posted by @amorriscode in https://github.com/langaracs/course-resources/pull/8#issuecomment-1073361073_
